### ISSUE TITLE
Presentation created

### ISSUE THREAD

**Issue by jessdiallo** [jessdiallo/Assignment-8#1]
Hi @mdscheuerell,

I've created a presentation using R Markdown according to the Assignment 8 instructions.
Thanks!

**Comment by mdscheuerell** [comment]
Nice job, Jess! I especially liked the photo of you—is that Utah canyon country?

**Comment by jessdiallo** [comment]
Thanks, Mark! @mdscheuerell 
Yes, it was in Little Wild Horse Canyon in Utah during a solo road trip I took across the US!
